version: "3.9"
services:
  mongo:
    image: mongo:7
    container_name: cookwithlove-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jovanoskalj
      - MONGO_INITDB_ROOT_PASSWORD=neu68BwU2yEN_gx
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: cookwithlove-backend
    restart: always
    ports:
      - "5050:5050"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./cookwithlove-frontend
    container_name: cookwithlove-frontend
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  mongo-data: